<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.17">
  <POU Name="FTP" Id="{bf44cf0a-6eab-48bb-bb6c-a7ceca0b3221}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FTP
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//https://download.beckhoff.com/download/document/automation/twincat3/TF6300_TC3_FTP_CLIENT_EN.pdf
]]></ST>
    </Implementation>
    <LineIds Name="FTP">
      <LineId Id="5" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>